######################################################################
# Automatically generated by qmake (2.00a) mar oct 11 15:33:51 2005
######################################################################

CONFIG+=qttest
TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += testsudoku.h ../src/sudoku.h  ../src/sudoku.cpp
SOURCES += testsudoku.cpp ../src/sudoku.cpp
CONFIG+=qttest
